progs: Comment out gallium/raw/SConscript from progs/SConscript.
Commit db5c2235d1accc2adcf1746aec2342bfa67237ba broke the default SCons
build.
NameError: name 'graw' is not defined:

This patch allows the default SCons build to work again until a proper
fix is available.