mesa/sso: Fix typo of 'unsigned'.
Fix build error introduced with commit f4c13a890fa24ff1f998e7cac0ecc31505a29403.

  CC       pixeltransfer.lo
main/pipelineobj.c: In function '_mesa_delete_pipeline_object':
main/pipelineobj.c:59:4: error: unknown type name 'unsinged'
    unsinged i;
    ^

Signed-off-by: Vinson Lee <vlee@freedesktop.org>