mesa: Fix DEBUG_MATH build on sparc.
Need to use '__asm__' instead of plain 'asm'.

math/m_debug_clip.c: In function ‘test_cliptest_function’:
math/m_debug_clip.c:253: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘asm’
math/m_debug_clip.c:253: warning: implicit declaration of function ‘asm’

Signed-off-by: David S. Miller <davem@davemloft.net>